/**
 * Static registry of built-in themes.
 *
 * By importing configs and layouts statically, Bun's bundler includes them
 * in the compiled binary. Assets and content are embedded as base64 via
 * the generated embedded-assets.ts module.
 */
import * as fs from "node:fs";
import * as path from "node:path";

// Static imports — configs
import bookConfig from "../../themes/book/config.ts";
import basicConfig from "../../themes/basic/config.ts";

// Static imports — layouts
import bookIndex from "../../themes/book/layout/index.ts";
import bookPrint from "../../themes/book/layout/print.ts";
import basicIndex from "../../themes/basic/layout/index.ts";

// Embedded binary data (generated by scripts/generate-embedded.ts)
import { embeddedAssets, embeddedContent } from "./embedded-assets.ts";

export const BUILTIN_THEME_NAMES = ["book", "basic"] as const;
export type BuiltinThemeName = (typeof BUILTIN_THEME_NAMES)[number];

export const builtinConfigs: Record<BuiltinThemeName, any> = {
  book: bookConfig,
  basic: basicConfig,
};

const builtinLayouts: Record<string, Record<string, Function>> = {
  book: {
    "index.ts": bookIndex,
    "print.ts": bookPrint,
  },
  basic: {
    "index.ts": basicIndex,
  },
};

export function isBuiltinTheme(name: string): name is BuiltinThemeName {
  return BUILTIN_THEME_NAMES.includes(name as BuiltinThemeName);
}

/**
 * Get a layout function for a built-in theme.
 * @param themeName - e.g. "book"
 * @param layoutFile - e.g. "index.ts" or "print.ts"
 */
export function getBuiltinLayout(
  themeName: string,
  layoutFile: string,
): Function | null {
  return builtinLayouts[themeName]?.[layoutFile] ?? null;
}

/**
 * Extract embedded asset files for a built-in theme to a target directory.
 */
export async function extractBuiltinAssets(
  themeName: string,
  targetDir: string,
): Promise<void> {
  const files = embeddedAssets[themeName];
  if (!files) return;
  await extractFiles(files, targetDir);
}

/**
 * Extract embedded content files for a built-in theme to a target directory.
 */
export async function extractBuiltinContent(
  themeName: string,
  targetDir: string,
): Promise<void> {
  const files = embeddedContent[themeName];
  if (!files) return;
  await extractFiles(files, targetDir);
}

async function extractFiles(
  files: Record<string, string>,
  targetDir: string,
): Promise<void> {
  for (const [relativePath, base64Data] of Object.entries(files)) {
    const outPath = path.join(targetDir, relativePath);
    fs.mkdirSync(path.dirname(outPath), { recursive: true });
    fs.writeFileSync(outPath, Buffer.from(base64Data, "base64"));
  }
}
