/**
 * Build-time script that reads all theme asset and content files,
 * encodes them as base64, and generates src/themes/embedded-assets.ts.
 *
 * Run before `bun build --compile` to embed theme files in the binary.
 */
import * as fs from "node:fs";
import * as path from "node:path";

const THEMES_DIR = path.join(import.meta.dir, "../themes");
const OUTPUT_FILE = path.join(import.meta.dir, "../src/themes/embedded-assets.ts");

function walkDir(dir: string): string[] {
  const results: string[] = [];
  if (!fs.existsSync(dir)) return results;

  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...walkDir(fullPath));
    } else {
      results.push(fullPath);
    }
  }
  return results;
}

function encodeFiles(baseDir: string): Record<string, string> {
  const files: Record<string, string> = {};
  if (!fs.existsSync(baseDir)) return files;

  for (const filePath of walkDir(baseDir)) {
    const relativePath = path.relative(baseDir, filePath);
    const content = fs.readFileSync(filePath);
    files[relativePath] = content.toString("base64");
  }
  return files;
}

// Discover themes
const themeNames = fs.readdirSync(THEMES_DIR, { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => d.name);

const assets: Record<string, Record<string, string>> = {};
const content: Record<string, Record<string, string>> = {};

for (const theme of themeNames) {
  assets[theme] = encodeFiles(path.join(THEMES_DIR, theme, "assets"));
  content[theme] = encodeFiles(path.join(THEMES_DIR, theme, "content"));
}

const output = `// Auto-generated by scripts/generate-embedded.ts — do not edit
export const embeddedAssets: Record<string, Record<string, string>> = ${JSON.stringify(assets, null, 2)};

export const embeddedContent: Record<string, Record<string, string>> = ${JSON.stringify(content, null, 2)};
`;

fs.writeFileSync(OUTPUT_FILE, output);
console.log(`Generated ${OUTPUT_FILE} (${themeNames.join(", ")})`);
