export default function(site) {
  return `
    <nav>
      <ul>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
        <li>sdjhfkhsdf</li>
      </ul>
    </nav>
  `;
}
